#!/usr/bin/env python

import argparse

import models
from utils import open_cmdline_file, close_cmdline_file

parser = argparse.ArgumentParser()
parser.add_argument('--workdir', required=True, help='Train the model in this directory.')
parser.add_argument('--text', required=True, help='Train the model on these terminals.')
parser.add_argument('--tags', required=True, help='Use these tags for the given terminals.')
parser.add_argument('--model', required=True, help='Write the model to this file.')

def main():
    args = parser.parse_args()
    corpus = [l.strip().split() for l in open_cmdline_file(args.text)]
    tags = [l.strip().split() for l in open_cmdline_file(args.tags)]
    
    model_file = open_cmdline_file(args.model, mode='w')
    model_file.write('foobar\n')
    close_cmdline_file(model_file)

if __name__ == '__main__': main()
